name: can-cache-stack

services:
  can-cache-agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    container_name: can-cache-agent
    environment:
      AGENT_LISTEN_HOST: 0.0.0.0
      AGENT_LISTEN_PORT: 11211
      AGENT_REGISTRATION_ENABLED: "true"
      AGENT_REGISTRATION_HOST: 0.0.0.0
      AGENT_REGISTRATION_PORT: 11311
      AGENT_DISCOVERY_DNS: localhost
      AGENT_DASHBOARD_MODE: logs
      QUARKUS_LOG_LEVEL: INFO
    ports:
      - "127.0.0.1:8080:8080"
      - "11211:11211"
      - "11311:11311"
    networks:
      - can-cache-net

  can-cache-app-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: can-cache-app-1
    environment:
      APP_NETWORK_PORT: 11212
      APP_AGENT_ENABLED: "true"
      APP_AGENT_HOST: can-cache-agent
      APP_AGENT_PORT: 11211
      APP_AGENT_REGISTRATION_PORT: 11311
      APP_AGENT_ADVERTISED_HOST: can-cache-app-1
      APP_CLUSTER_DISCOVERY_NODE_ID: can-cache-app-1
      APP_CLUSTER_REPLICATION_ADVERTISE_HOST: can-cache-app-1
      APP_CLUSTER_REPLICATION_FACTOR: "2"
    depends_on:
      - can-cache-agent
    networks:
      - can-cache-net

  can-cache-app-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: can-cache-app-2
    environment:
      APP_NETWORK_PORT: 11212
      APP_AGENT_ENABLED: "true"
      APP_AGENT_HOST: can-cache-agent
      APP_AGENT_PORT: 11211
      APP_AGENT_REGISTRATION_PORT: 11311
      APP_AGENT_ADVERTISED_HOST: can-cache-app-2
      APP_CLUSTER_DISCOVERY_NODE_ID: can-cache-app-2
      APP_CLUSTER_REPLICATION_ADVERTISE_HOST: can-cache-app-2
      APP_CLUSTER_REPLICATION_FACTOR: "2"
    depends_on:
      - can-cache-agent
    networks:
      - can-cache-net


networks:
  can-cache-net:
    driver: bridge
